### ISSUE TITLE
ユーザが退会できるようにする

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#12]
## 概要
ユーザが退会できるようにする

期待する結果や、なぜそれが必要なのかについて説明する
画面の作成・変更が伴う場合は図やスクリーンショットを用いて説明する

## タスク
- [ ] 細かいタスクに分解できているなら書き出す

## 補足
その他伝えたいこと、見てもらいたい資料、関連するIssueなどあれば書く

**Comment by itkrt2y** [comment]
実装方針ですが、ユーザーをdeleteしてしまうとそのユーザーのプロジェクトからforkされたプロジェクトの扱いなどで多分死ねるので、ダミーデータで上書きするのがいいと思います
