### ISSUE TITLE
（バグ？）レシピから写真を削除すると、挙動が不安定になる。

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#20]
## 概要
ブラウザ側の表示が更新されないことがある。（画像が残っている）

不具合の説明を文章やスクリーンショットなどを使って説明する

## 再現手順
手順をわかりやすく書く

## 原因
わかれば

## 修正案
わかれば

## 補足
その他伝えたいこと、見てもらいたい資料、関連するIssueなどあれば書く

**Comment by itkrt2y** [comment]
カルーセルのbootstrap移行により、多分直っている。
元々の再現方法が不明なので、確信は持てないのだが......

**Comment by takeyuweb** [comment]
修正済み
