### ISSUE TITLE
「More Projects」リンクの表示

### ISSUE THREAD

**Issue by noriyotcp** [takeyuwebinc/gitfab2#46]
## 概要
#36 がマージされた後に取り組む
~~`projects/` 配下のパーシャルが多すぎるのでまとめる~~

「最近のプロジェクト」の下の`More Projects` というリンクを表示するようにする
- クエリ無しの検索結果画面の2ページへと遷移する

https://github.com/takeyuwebinc/gitfab2/blob/90cf4e103eeb858a952e779cf0c5d80098d7f07a/app/views/projects/_recent_projects.html.slim#L7

`@project` は12個までしか取得されないので、条件に一致せず、現在は表示されていない

## タスク
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by itkrt2y** [comment]
パーシャルが多いのは鬱陶しいですが、パーシャルに分けることで変数の生存範囲を明示できたりとコンポーネント的なメリットもあるので、無条件にまとめるのはあまり同意できません。
「パーシャルのrenderが遅いのでループで使うのはやめる」とか明確な理由があるならば、ありです。

**Comment by noriyotcp** [comment]
わかりました。More Projectsのリンク表示のみにします
