### ISSUE TITLE
削除したはずのグループ名がフォーク先で表示される

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#66]
## 概要
削除されたグループ名が表示される

![image](https://user-images.githubusercontent.com/60980/47698302-28847b00-dc52-11e8-9cb2-7d4044423328.png)

## 再現手順
1. グループ作成
2. 1のグループでプロジェクト作成
3. 2のプロジェクトをフォーク
4. 1のグループを削除
5. 3でフォークしたプロジェクトページを確認

This project was forked from `削除されたはずのグループ名/Deleted Project` と表示される

**Comment by itkrt2y** [comment]
直しました
