### ISSUE TITLE
プロジェクトへのコメント投稿者のプロフィールページへのリンクが誤り

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#67]
## 概要
プロジェクトページ下部のコメント欄に投稿したユーザー名に設定されてあるリンクが誤り

![image](https://user-images.githubusercontent.com/60980/47700449-d9424880-dc59-11e8-9516-91bb0743bd22.png)

`https://localhost:3000/projects.takeyuweb` になる

## 再現手順
1. ログイン
2. 適当なプロジェクトページを開く
3. コメント投稿
4. コメント投稿者名をクリック

リンク切れエラー

## 原因
https://github.com/takeyuwebinc/gitfab2/blob/master/app/views/projects/_project_comments.html.slim#L16 ここかな

**Comment by itkrt2y** [comment]
修正しました https://github.com/takeyuwebinc/gitfab2/commit/7580719fa34c57348a04a1e7b616200e926ef4e4
