### ISSUE TITLE
開発環境でSNSシェアボタンを押すと NOT FOUND

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#77]
## 概要
![share](https://user-images.githubusercontent.com/60980/49568471-6a50c180-f974-11e8-98e9-fc80e71c9f97.gif)

## 再現手順
https://dev.fabble.cc/samplesample/hogehoge にアクセス
シェアボタンを押す

## 原因
シェアされるURLのホスト名までが `https://fabble.cc` 決め打ちである

## 修正案
アクセスに使用されているホスト名を使うようにする
`project_url(project)` でいけないですか？

**Comment by itkrt2y** [comment]
@takeyuweb 修正しました https://github.com/takeyuwebinc/gitfab2/commit/963d8edd0fc36faf5d3be6f1ca7f47b4136bc4b7
