### ISSUE TITLE
バックアップファイル作成日時の横にタイムゾーンを表示

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#78]
## 概要
> 朝11時にバックアップの作成をすると、2時時点のバックアップを作成した、と表示されるため、ユーザーとしてちょっと、ドキッとするかな、と思いました。

>> 日本時間で表示するかタイムゾーンを表示した方がよいですね
> 
> こちら使うの日本の方だけではないでしょうし、そうなるとタイムゾーンを表示する、の方がいいですかね

![image](https://user-images.githubusercontent.com/60980/49568693-0f6b9a00-f975-11e8-99af-18b2e43b7586.png)

## タスク
- [x] ビューの修正

**Comment by itkrt2y** [comment]
@takeyuweb 修正しました https://github.com/takeyuwebinc/gitfab2/commit/3a07d837ab56d7c0a705499bc98da1d7a2788e02
