### ISSUE TITLE
「最近のプロジェクト」にプライベートプロジェクトが表示される

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#93]
## 概要

タイトルの通り

![image](https://user-images.githubusercontent.com/60980/52959552-cbb3f880-33d9-11e9-88ed-de986c2c7add.png)

## 再現手順
1. 新しいプロジェクトを作成
2. プライベートプロジェクトにする
3. トップページを確認

### 期待する結果

プライベートプロジェクトは表示されない

### 発生する事象

プライベートプロジェクトが表示される

## 原因
https://github.com/takeyuwebinc/gitfab2/commit/dbc3c5902cdebc6e3a257ef616a2cca43548a145
これで `.published` が外れたためだと思われる

**Comment by itkrt2y** [comment]
@takeyuweb 修正しました

**Comment by takeyuweb** [comment]
確認しました。
