### ISSUE TITLE
アクセス数データ投入タスク

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/gitfab2#95]
## 概要
次の形式のCSVの提供を受け、初期データとして入力する。

```csv
/fabble/tutorial,1234
/takeyuweb/sample,123
```

`オーナーの識別子/プロジェクトの識別子`,`過去30日のアクセス数合計`

`過去30日のアクセス数合計` は30日分に均等にわけて登録する。

たとえば、 `1000` であれば過去30日、１日あたり `33` のアクセスを登録する。

プロジェクトが見つからない場合は、どの行（どのURL）が見つからなかったか、標準出力に表示してスキップしてください。

タスクの実行はマニュアルオペレーションとして、本番適用時に作業者がコンソールで実行することとする。

**Comment by noriyotcp** [comment]
@takeyuweb
質問ですが、コンソールとはRails console ではなくて、通常のコンソールのことでしょうか

**Comment by takeyuweb** [comment]
@noriyotcp はい。SSHでログインしてたたきます。
別にRails consoleでも `rails c` してたたくだけなのでかまいませんが、rakeタスクを使う想定でした。
